const SEARCH_REQUESTED = 'STOCK_SEARCH_REQUESTED';
const UPDATE_SEARCH_RESULTS = 'STOCK_SEARCH_UPDATE_RESULTS';
const UPDATE_SEARCH_VALUE = 'STOCK_SEARCH_UPDATE_SEARCH_VALUE';

const actions = {
    SEARCH_REQUESTED,
    UPDATE_SEARCH_RESULTS,
    UPDATE_SEARCH_VALUE
};

export default actions;